apiVersion: v1
kind: ConfigMap
metadata:
  name: safespace-config
  namespace: anything-but-revisi
  labels:
    app: safespace-backend
data:
  DB_HOST: "103.185.52.138"
  DB_PORT: "1185"
  DB_NAME: "anything_but_revisi"
  DB_USER: "anything_but_revisi"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  
  # Variabel baru yang ditambahkan dari .env
  DB_POOL_MIN_SIZE: "10"
  DB_POOL_MAX_SIZE: "20"
  DB_QUERY_TIMEOUT: "30"
  DB_CONNECTION_TIMEOUT: "10"
  ENVIRONMENT: "development"
  LOG_LEVEL: "INFO"