apiVersion: v1
kind: Service
metadata:
  name: safespace-backend
  namespace: anything-but-revisi
  labels:
    app: safespace-backend
spec:
  type: ClusterIP
  selector:
    app: safespace-backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
